### ISSUE TITLE
Create About Us Page for Meme Hunt to Highlight Team Information

### ISSUE THREAD

**Issue by TopCoderAriaChen** [TopCoderAriaChen/CITS5505-Group-Project#2]
We need an "About Us" page for our Meme Hunt application that introduces our team members and provides a personal touch. This page should offer insights into our team’s composition and highlight the contributions of each member. The page should immerse visitors in the playful, game-like aesthetic of our Meme Hunt application.

**Comment by raunakchhabra** [comment]
[fr.zip](https://github.com/TopCoderAriaChen/CITS5505-Group-Project/files/15328526/fr.zip)
