### ISSUE TITLE
Choosing the best answer from the replys

### ISSUE THREAD

**Issue by TingChen-TC** [TopCoderAriaChen/CITS5505-Group-Project#3]
Implement the functionality for requesters to choose the best response from multiple submissions in response to their image request. This feature is crucial for rewarding users with points based on the quality and relevance of their submissions.

**Comment by yuanxichennn** [comment]
Yes, We need to implement a feature that allows requesters to select the best response from multiple submissions in response to their image request. This feature should reward users with points based on the quality and relevance of their submissions.
