### ISSUE TITLE
About Us Page Link Not Working

### ISSUE THREAD

**Issue by TopCoderAriaChen** [TopCoderAriaChen/CITS5505-Group-Project#7]
The link to the "About Us" page is non-functional. When attempting to access the "About Us" page via the provided link in the navigation bar, it fails to redirect to the correct page.

**Comment by yuanxichennn** [comment]
- Check the Blueprint Configuration:
Ensure that the "About Us" page is correctly registered in the Flask blueprints. Verify that the route for the "About Us" page is defined properly in the application.

- Verify the Template:
Ensure that the about-us.html exists in the correct front-end directory and reference.

**Comment by raunakchhabra** [comment]
about us page frontend: missing detailed instruction/ user manual for normal users to read - DONE ✅
