### ISSUE TITLE
Posting button for sending remarks/hunts not working

### ISSUE THREAD

**Issue by yuanxichennn** [TopCoderAriaChen/CITS5505-Group-Project#9]
The form submission functionality for posting comments on the post_detail.html page is not working as expected. When the user fills out the form and clicks the "Post" button, the form does not submit and no new comments are added.

**Steps to Reproduce:**
- Navigate to the post detail page.
- Scroll down to the "Post Remark" section.
- Fill out the comment form with content.
- Click the "Post" button.
- Observe that the form does not submit and the comment is not added.

**Expected Behavior:**
Upon clicking the "Post" button, the form should submit, and the new comment should be added to the post's remarks.

**Observed Behavior:**
Clicking the "Post" button does not trigger form submission, and no new comments are added.

<img width="887" alt="post" src="https://github.com/TopCoderAriaChen/CITS5505-Group-Project/assets/132573064/2f1837d6-d050-4f32-b082-bf84a82bb6a8">

**Comment by TopCoderAriaChen** [comment]
This bug has been fixed. Good Job!
